/**
 * Script to import property data from Google Sheets CSV export
 *
 * Usage:
 * 1. Export your Google Sheet as CSV
 * 2. Save it as 'property-data-import.csv' in the scripts folder
 * 3. Run: npx ts-node scripts/import-property-data.ts
 * 4. This will generate the updated property-data.ts file
 */

import * as fs from 'fs';
import * as path from 'path';

interface CSVRow {
  asset_name: string;
  asset_slug: string;
  category: string;
  country: string;
  region: string;
  city: string;
  guest_max: string;
  bedrooms: string;
  bathrooms: string;
  overview_100w: string;
  display_from_price_usd: string;
  rate_notes: string;
  min_stay_nights: string;
  amenities_list: string;
  iCal: string;
}

function parseCSV(csvContent: string): CSVRow[] {
  const lines = csvContent.split('\n');
  const headers = lines[0].split('\t').map(h => h.trim());
  const rows: CSVRow[] = [];

  for (let i = 1; i < lines.length; i++) {
    if (!lines[i].trim()) continue;

    const values = lines[i].split('\t');
    const row: any = {};

    headers.forEach((header, index) => {
      row[header] = values[index]?.trim() || '';
    });

    // Skip empty rows
    if (!row.asset_name || !row.asset_slug) continue;

    rows.push(row as CSVRow);
  }

  return rows;
}

function normalizeCategory(category: string): string {
  const normalized = category.toLowerCase().trim();
  if (['villa', 'yacht', 'transport', 'property', 'hotel'].includes(normalized)) {
    return normalized;
  }
  return 'property';
}

function parseNumber(value: string): number | null {
  if (!value || value.toLowerCase() === 'na') return null;
  const parsed = parseFloat(value);
  return isNaN(parsed) ? null : parsed;
}

function parseAmenities(amenitiesList: string): string[] {
  if (!amenitiesList) return [];
  return amenitiesList
    .split(/[;,]/)
    .map(a => a.trim())
    .filter(a => a.length > 0);
}

function generatePropertyDataCode(rows: CSVRow[]): string {
  let code = `/**
 * Property data from Google Sheets - Website Collection MASTER
 * Auto-generated by scripts/import-property-data.ts
 * Maps asset slugs to pricing, specs, and amenity data
 */

export interface PropertyData {
  assetName: string;
  assetSlug: string;
  category: 'villa' | 'yacht' | 'transport' | 'property' | 'hotel';
  country: string;
  region: string;
  city: string;
  guestMax: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  overview: string;
  displayPrice: string;
  rateNotes?: string;
  minStayNights: number | null;
  amenities: string[];
  icalUrl?: string;
}

export const PROPERTY_DATA: Record<string, PropertyData> = {\n`;

  rows.forEach((row, index) => {
    const category = normalizeCategory(row.category);
    const guestMax = parseNumber(row.guest_max);
    const bedrooms = parseNumber(row.bedrooms);
    const bathrooms = parseNumber(row.bathrooms);
    const minStayNights = parseNumber(row.min_stay_nights);
    const amenities = parseAmenities(row.amenities_list);

    code += `  '${row.asset_slug}': {\n`;
    code += `    assetName: ${JSON.stringify(row.asset_name)},\n`;
    code += `    assetSlug: ${JSON.stringify(row.asset_slug)},\n`;
    code += `    category: ${JSON.stringify(category)},\n`;
    code += `    country: ${JSON.stringify(row.country)},\n`;
    code += `    region: ${JSON.stringify(row.region)},\n`;
    code += `    city: ${JSON.stringify(row.city)},\n`;
    code += `    guestMax: ${guestMax},\n`;
    code += `    bedrooms: ${bedrooms},\n`;
    code += `    bathrooms: ${bathrooms},\n`;
    code += `    overview: ${JSON.stringify(row.overview_100w)},\n`;
    code += `    displayPrice: ${JSON.stringify(row.display_from_price_usd)},\n`;

    if (row.rate_notes) {
      code += `    rateNotes: ${JSON.stringify(row.rate_notes)},\n`;
    }

    code += `    minStayNights: ${minStayNights},\n`;
    code += `    amenities: ${JSON.stringify(amenities)},\n`;

    if (row.iCal) {
      code += `    icalUrl: ${JSON.stringify(row.iCal)},\n`;
    }

    code += `  },\n`;
  });

  code += `};

/**
 * Get property data by WordPress slug
 */
export function getPropertyDataBySlug(slug: string): PropertyData | null {
  // Normalize slug (remove "- Preview" suffix if present)
  const normalizedSlug = slug
    .replace(/-preview-\\d+$/, '')
    .replace(/-preview$/, '')
    .toLowerCase();

  return PROPERTY_DATA[normalizedSlug] || null;
}

/**
 * Extract price number from display price string
 */
export function extractPriceNumber(displayPrice: string): number | null {
  const match = displayPrice.match(/\\$([0-9,]+)/);
  if (match) {
    return parseInt(match[1].replace(/,/g, ''), 10);
  }
  return null;
}
`;

  return code;
}

async function main() {
  const csvPath = path.join(__dirname, 'property-data-import.csv');
  const outputPath = path.join(__dirname, '..', 'data', 'property-data.ts');

  // Check if CSV exists
  if (!fs.existsSync(csvPath)) {
    console.error(`❌ CSV file not found: ${csvPath}`);
    console.log('\nTo use this script:');
    console.log('1. Export your Google Sheet as CSV (tab-separated)');
    console.log('2. Save it as: scripts/property-data-import.csv');
    console.log('3. Run: npx ts-node scripts/import-property-data.ts');
    process.exit(1);
  }

  console.log('📖 Reading CSV file...');
  const csvContent = fs.readFileSync(csvPath, 'utf-8');

  console.log('🔄 Parsing property data...');
  const rows = parseCSV(csvContent);
  console.log(`✅ Found ${rows.length} properties`);

  console.log('🏗️  Generating TypeScript code...');
  const code = generatePropertyDataCode(rows);

  console.log('💾 Writing to property-data.ts...');
  fs.writeFileSync(outputPath, code, 'utf-8');

  console.log(`\n✅ Successfully generated ${outputPath}`);
  console.log(`📊 Total properties: ${rows.length}`);
  console.log('\nProperty types:');

  const categories = rows.reduce((acc, row) => {
    const cat = normalizeCategory(row.category);
    acc[cat] = (acc[cat] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  Object.entries(categories).forEach(([cat, count]) => {
    console.log(`  - ${cat}: ${count}`);
  });
}

main().catch(error => {
  console.error('❌ Error:', error);
  process.exit(1);
});
